version: "3.1"
services:
  api:
    build: .
    environment:
      MYSQL_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"